
(function(){const $=id=>document.getElementById(id);
/* ---------- 1. Tableau de bord : 4 bulles verticales ---------- */
const dash=$('v9Dash'),dov=$('v9DashOv');
function dashToggle(force){const on=force!==undefined?force:!dash.classList.contains('on');dash.classList.toggle('on',on);dov.classList.toggle('on',on);if(window.v7UpdateNav)window.v7UpdateNav();}
dov.onclick=()=>dashToggle(false);
dash.querySelectorAll('[data-go]').forEach(b=>b.onclick=async()=>{dashToggle(false);{const n=$('nb');if(n&&!n.hidden)n.hidden=true;}document.body.classList.remove('reading-only');if(window.closeDrawer)closeDrawer();if(window.closeSheet)closeSheet();const ws=$('workSearch');if(ws&&!ws.hidden&&$('workClose'))$('workClose').click();if(window.GarageStudy)await GarageStudy.open(b.dataset.go);if(window.v7UpdateNav)v7UpdateNav();});
const dashClick=()=>{const sp=$('studyPanel'),ws=$('workSearch');if(ws&&!ws.hidden){dashToggle(false);if(window.v7Center)v7Center();return;}dashToggle();};
setInterval(()=>{const c=$('wmbNavDash');if(c&&c.onclick!==dashClick)c.onclick=dashClick;},400);
document.addEventListener('keydown',e=>{if(e.key==='Escape')dashToggle(false)});
/* ---------- 2/3/4. Sélection : bulles compactes + palette 5 couleurs + annotation existante ---------- */
const tools=$('wmbPassageTools'),sel=$('v9Sel'),pal=$('v9Pal'),hint=$('v9Hint');let mode='highlight',last={x:24,y:180};
document.addEventListener('pointerdown',e=>{if(e.target.closest('#bibleView .vt,#msgView .pt'))last={x:e.clientX,y:e.clientY}},{passive:true,capture:true});
function place(){const w=Math.min(300,innerWidth-16),h=sel.offsetHeight||120;const sp=[...document.querySelectorAll('.wmb-dotted')];let top=-1,bot=-1;if(sp.length){const rs=sp.map(e=>e.getBoundingClientRect()).filter(r=>r.width||r.height);if(rs.length){top=Math.min(...rs.map(r=>r.top));bot=Math.max(...rs.map(r=>r.bottom));}}let x=(innerWidth-w)/2,y=(innerHeight-h)/2;if(top>=0&&y<bot+8&&y+h>top-8){y=(bot+10+h<=innerHeight-90)?bot+10:top-h-10;}if(y<70)y=70;if(y+h>innerHeight-8)y=innerHeight-h-8;sel.style.left=x+'px';sel.style.top=y+'px';}
function existing(){const marks=(window.GarageFeatures?GarageFeatures.getAnnotations():[]),units=window.WMBMarks?WMBMarks.getSelection():[];return marks.filter(n=>units.some(u=>u.key===n.key&&n.end>u.start&&n.start<u.end));}
function paintExisting(){const ex=existing();const hi=ex.filter(n=>n.type==='highlight'),un=ex.filter(n=>n.type==='underline');$('v9Hi').classList.toggle('on',hi.length>0);$('v9Un').classList.toggle('on',un.length>0);
 const cur=(mode==='highlight'?hi:un).map(n=>n.color.toLowerCase());const presets=['#9be07a','#ffe066','#ff9a9a','#a8ceff'],extra=cur.filter(c=>!presets.includes(c));pal.querySelectorAll('.sw:not(.mix)').forEach(s=>s.classList.toggle('has',cur.includes(s.dataset.c)));{const cu=$('v9Cust'),ci=$('v9CustIn');if(cu){cu.classList.toggle('has',extra.length>0);if(extra.length&&ci){ci.value=extra[0];cu.style.setProperty('--cc',extra[0]);}}}$('v9Del').hidden=!(mode==='highlight'?hi.length:un.length);
 hint.textContent=ex.length?('Annotation existante : '+(hi.length?'surlignage ':'')+(un.length?'soulignement ':'')+'— choisissez une couleur pour la changer, 🗑 pour la retirer.'):'';}
function openPal(m){mode=m;pal.classList.add('on');paintExisting();place();}
function apply(color){const useH=mode==='highlight';$('wmbUseHighlight').checked=useH;$('wmbUseUnderline').checked=!useH;
 $(useH?'wmbHighlightColor':'wmbUnderlineColor').value=color;
 $('wmbApply').click();setTimeout(()=>{if(window.WMBMarks)WMBMarks.close();},60);}
function erase(){$('wmbUseHighlight').checked=mode==='highlight';$('wmbUseUnderline').checked=mode==='underline';$('wmbErase').click();setTimeout(()=>{if(window.WMBMarks)WMBMarks.close();},60);}
$('v9Hi').onclick=()=>openPal('highlight');$('v9Un').onclick=()=>openPal('underline');$('v9Cp').onclick=()=>{$('wmbCopy').click();hint.textContent='Texte copié.';setTimeout(()=>{if(window.WMBMarks)WMBMarks.close();},500);};$('v9X').onclick=()=>{if(window.WMBMarks)WMBMarks.close();};
pal.querySelectorAll('.sw:not(.mix)').forEach(s=>s.onclick=()=>apply(s.dataset.c));$('v9Del').onclick=erase;
{const ci=$('v9CustIn'),cu=$('v9Cust');if(ci&&cu){try{const sv=localStorage.getItem('m4-custom-mark');if(sv&&/^#[0-9a-f]{6}$/i.test(sv))ci.value=sv;}catch(e){}cu.style.setProperty('--cc',ci.value);
 ci.addEventListener('input',()=>cu.style.setProperty('--cc',ci.value));
 ci.addEventListener('change',()=>{const c=ci.value.toLowerCase();cu.style.setProperty('--cc',c);try{localStorage.setItem('m4-custom-mark',c)}catch(e){}apply(c);});}}
sel.querySelectorAll('button').forEach(b=>b.onpointerdown=e=>e.preventDefault());
if(tools){new MutationObserver(()=>{const on=!tools.hidden;sel.classList.toggle('on',on);if(on){pal.classList.remove('on');hint.textContent='';const ex=existing();$('v9Hi').classList.toggle('on',ex.some(n=>n.type==='highlight'));$('v9Un').classList.toggle('on',ex.some(n=>n.type==='underline'));if(ex.length){hint.textContent='Annotation existante — appuyez sur 🖍 ou ▁ pour la modifier ou la retirer.';}place();}}).observe(tools,{attributes:true,attributeFilter:['hidden']});
 const cnt=$('wmbSelectionCount');if(cnt)new MutationObserver(()=>{$('v9Cnt').textContent=cnt.textContent;paintExisting();}).observe(cnt,{childList:true,characterData:true,subtree:true});}
/* ---------- 5/7/8. Cercle Jésus → panneau Bible ; photo Branham → panneau brochures ---------- */
function setJesus(v){v=Math.max(30,Math.min(72,+v||44));document.documentElement.style.setProperty('--jesus',v+'px');try{localStorage.setItem('wmb-jesus',String(v))}catch(e){}const o=$('jesusVal');if(o)o.textContent=v+' px';const r=$('jesusRange');if(r&&+r.value!==v)r.value=v;}
setJesus((()=>{try{return localStorage.getItem('wmb-jesus')||44}catch(e){return 44}})());
let panel='bible';const drawer=$('drawer');
function paintDrawer(){if(typeof D==='undefined'||!D||!drawer)return;const q=($('dFind').value||'').trim(),fold=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),fq=fold(q);drawer.classList.toggle('v9-bible',panel==='bible');drawer.classList.toggle('v9-msg',panel==='msg');
 const ic=drawer.querySelector('.dh .round');if(ic){ic.innerHTML=panel==='bible'?'<img src="'+$('jesusPhoto').src+'" alt="">':'<img src="'+$('hdrPhoto').src+'" alt="">';}
 $('dFind').placeholder=panel==='bible'?'Rechercher un livre de la Bible…':'Rechercher une brochure (code ou titre)…';
 let h='';
 if(panel==='bible'){const B=D.books.map((b,i)=>i).filter(i=>!fq||fold(D.books[i][0]).includes(fq)||(window.ABBR&&fold(ABBR[i])===fq));
  h+='<div class="dsec">En lecture</div><div class="dit" data-b="'+S.book+'" style="background:#EEF2FF;border:2px solid var(--navy)">'+D.books[S.book][0]+' '+S.chap+'<small>'+D.books[S.book][1].length+' chapitres</small></div>';
  const g=(a,b)=>B.filter(i=>i>=a&&i<b).map(i=>'<button type="button" data-b="'+i+'" class="'+(i===S.book?'on':'')+'" title="'+D.books[i][0]+'">'+D.books[i][0]+'</button>').join('');
  const at=g(0,39),nt=g(39,66);if(at)h+='<div class="dsec">Ancien Testament</div><div class="v9-grid">'+at+'</div>';if(nt)h+='<div class="dsec">Nouveau Testament</div><div class="v9-grid">'+nt+'</div>';if(!at&&!nt)h+='<div style="padding:16px;color:var(--mut);font-size:13px">Aucun livre.</div>';
  h+='<div class="dsec">Bibles</div><div class="dit" style="background:#EEF2FF"><b>Bible</b></div>';}
 else{h+='<div class="v9-logo"><img src="'+$('hdrPhoto').src+'" alt=""><div><b>William Marrion Branham</b><small>'+D.meta.length+' brochures · 1947–1965 · Shekinah &amp; VGR</small></div></div>';
  if(S.doc!=null){const m=D.meta[S.doc];h+='<div class="dsec">En lecture</div><div class="dit" data-d="'+S.doc+'" style="background:var(--ink);color:#fff">'+m[0]+' '+m[1]+'<small>'+m[3]+' • '+m[5]+' §</small></div>';}
  let M=D.meta.map((m,i)=>i).filter(i=>!fq||fold(D.meta[i][0]+' '+D.meta[i][1]).includes(fq));const seen=new Set();M=M.filter(i=>{const k=D.meta[i][0];if(seen.has(k)&&D.meta[i][2]==='VGR')return false;seen.add(k);return true;});
  if(!M.length)h+='<div style="padding:16px;color:var(--mut);font-size:13px">Aucune brochure.</div>';
  let y='';M.slice(0,fq?300:1600).forEach(i=>{const m=D.meta[i],yy='19'+m[0].slice(0,2);if(yy!==y){y=yy;h+='<div class="v9-year">'+yy+'</div>';}h+='<div class="dit" data-d="'+i+'">'+m[0]+' '+m[1]+'<small>'+m[3]+' • '+(m[2]==='VGR'?'VGR':'Shekinah')+' • '+m[5]+' §</small></div>';});}
 $('dBody').innerHTML=h;
 $('dBody').querySelectorAll('[data-b]').forEach(e=>e.onclick=()=>{closeDrawer();const b=+e.dataset.b;goBible(b,b===S.book?S.chap:1,null)});
 $('dBody').querySelectorAll('[data-d]').forEach(e=>e.onclick=()=>{closeDrawer();openBrochure(+e.dataset.d,0,null)});}
function openPanel(which){panel=which;if(typeof D==='undefined'||!D)return;if(window.closeSheet)closeSheet();$('dFind').value='';drawer.style.transition='none';drawer.classList.remove('on');paintDrawer();void drawer.offsetWidth;drawer.style.transition='';drawer.classList.add('on');$('ov').classList.add('on');document.body.classList.add('panel-open');}
window.WMBOpenContextPanel=which=>openPanel(which==='msg'?'msg':'bible');
const bibleClick=e=>{e.preventDefault();e.stopImmediatePropagation();openPanel('bible');},msgClick=()=>openPanel('msg');
setInterval(()=>{const bd=$('btnDrawer');if(bd&&bd.onclick!==bibleClick)bd.onclick=bibleClick;const hp=$('hdrPhoto');if(hp&&hp.onclick!==msgClick){hp.onclick=msgClick;hp.title='Brochures W. M. Branham';}if(window.drawDrawer!==paintDrawerWrap)window.drawDrawer=paintDrawerWrap;},400);
const bf=$('bookFloat');/* la bulle basse-gauche garde son rôle Bible ⇄ Brochure */
if($('dFind'))$('dFind').addEventListener('input',()=>paintDrawer());
function paintDrawerWrap(){paintDrawer();}
/* ---------- 9/10/12. Recherche : ordre croissant/décroissant + paramètres ---------- */
function order(asc){if(typeof ascending==='undefined')return;if(ascending===asc){paintOrder();return;}if(typeof sortChanged==='function')sortChanged(sort);paintOrder();}
function paintOrder(){if(typeof ascending==='undefined')return;const a=$('v9Asc'),d=$('v9Desc');if(a)a.classList.toggle('on',ascending);if(d)d.classList.toggle('on',!ascending);}
if($('v9Asc')){$('v9Asc').onclick=()=>order(true);$('v9Desc').onclick=()=>order(false);setInterval(paintOrder,600);}
function getBub(){try{return +localStorage.getItem('wmb-bub')||54}catch(e){return 54}}
function setBub(v){v=Math.max(40,Math.min(80,+v||54));document.documentElement.style.setProperty('--bub',v+'px');try{localStorage.setItem('wmb-bub',v)}catch(e){}const r=$('bubRange'),l=$('bubVal');if(r)r.value=v;if(l)l.textContent=v+' px';}
setBub(getBub());
function bubHtml(){const v=getBub();return '<h3 style="margin-top:16px">Taille des bulles <span class="scale-val" id="bubVal">'+v+' px</span></h3><input type="range" id="bubRange" min="40" max="80" step="2" value="'+v+'"><div style="display:flex;justify-content:space-between;font-size:11px;color:var(--mut)"><span>Plus petites</span><span>Plus grandes</span></div><div style="display:flex;gap:6px;margin-top:8px"><button type="button" class="pres-opt" data-b="-2" style="flex:1;text-align:center">−</button><button type="button" class="pres-opt" data-b="0" style="flex:2;text-align:center">Taille par défaut (54 px)</button><button type="button" class="pres-opt" data-b="2" style="flex:1;text-align:center">+</button></div>';}
/* Bibliothèque en bulles (marquages, historiques) */
function bubblize(){return;const sc=$('studyContent');if(!sc)return;
 const ml=$('markList');if(ml&&!ml.querySelector('.v9-bubs')){const arts=[...ml.querySelectorAll('article.study-card')];if(arts.length){const g=document.createElement('div');g.className='v9-bubs';arts.forEach(a=>{const sp=a.querySelector('p span'),op=a.querySelector('[data-mark-open]'),de=a.querySelector('[data-mark-delete]'),st=sp?sp.getAttribute('style')||'':'';const hi=st.startsWith('background');const col=hi?st.slice(11).split(';')[0]:(st.match(/underline 3px (.*)$/)||[])[1]||'#999';const b=document.createElement('div');b.className='v9-bub';b.innerHTML='<div class="ic">'+(hi?'<div class="dot" style="background:'+col+'"></div>':'<div class="ul" style="background:'+col+'"></div>')+'</div><small>'+(a.querySelector('b')?.textContent||'')+'</small><small style="font-weight:500;opacity:.75">'+(sp?sp.textContent.slice(0,26)+(sp.textContent.length>26?'…':''):'')+'</small><button class="x" type="button" aria-label="Retirer">✕</button>';b.querySelector('.ic').onclick=()=>op&&op.click();b.querySelector('.x').onclick=()=>de&&de.click();g.append(b);a.classList.add('v9-hidden');});ml.append(g);}}
 sc.querySelectorAll('section').forEach(sec=>{if(sec.querySelector('.v9-bubs'))return;const arts=[...sec.querySelectorAll('article.study-card')];if(!arts.length)return;const isS=/Recherches/.test(sec.querySelector('h3')?.textContent||'');const g=document.createElement('div');g.className='v9-bubs';arts.forEach(a=>{const op=a.querySelector('[data-history-open]'),de=a.querySelector('[data-history-delete]');const b=document.createElement('div');b.className='v9-bub';b.innerHTML='<div class="ic">'+(isS?'<svg width="26" height="26" viewBox="0 0 32 32" fill="none" stroke="#353535" stroke-width="2.5" stroke-linecap="round"><circle cx="13" cy="13" r="9"/><path d="m20 20 8 8"/></svg>':'<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#353535" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 5h6a3 3 0 0 1 3 3v12a2 2 0 0 0-2-2H4z"/><path d="M20 5h-6a3 3 0 0 0-3 3v12a2 2 0 0 1 2-2h7z"/></svg>')+'</div><small>'+(op?op.textContent:'')+'</small><small style="font-weight:500;opacity:.7">'+(a.querySelector('small')?.textContent||'').slice(0,16)+'</small><button class="x" type="button" aria-label="Supprimer">✕</button>';b.querySelector('.ic').onclick=()=>op&&op.click();b.querySelector('.x').onclick=()=>de&&de.click();g.append(b);a.classList.add('v9-hidden');});sec.querySelector('.study-muted')?.after(g);});}
function settingsCard(){const c=document.createElement('section');c.className='pres-card';c.id='v9SetCard';const v=(()=>{try{return localStorage.getItem('wmb-jesus')||44}catch(e){return 44}})();
 c.innerHTML='<h3>Cercle Jésus (en-tête) <span class="scale-val" id="jesusVal">'+v+' px</span></h3><input type="range" id="jesusRange" min="30" max="72" step="2" value="'+v+'"><div style="display:flex;justify-content:space-between;font-size:11px;color:var(--mut)"><span>Plus petit</span><span>Plus grand</span></div><div style="display:flex;gap:6px;margin-top:8px"><button type="button" class="pres-opt" data-j="-2" style="flex:1;text-align:center">−</button><button type="button" class="pres-opt" data-j="0" style="flex:2;text-align:center">Taille par défaut (44 px)</button><button type="button" class="pres-opt" data-j="2" style="flex:1;text-align:center">+</button></div>'
+bubHtml();
 c.querySelector('#jesusRange').oninput=e=>setJesus(e.target.value);c.querySelectorAll('[data-j]').forEach(b=>b.onclick=()=>{const d=+b.dataset.j;setJesus(d?(+$('jesusRange').value+d):44)});
 const paintP=()=>{if(typeof selectedPeriods==='undefined')return;c.querySelectorAll('[data-p]').forEach(b=>{const p=b.dataset.p;b.classList.toggle('on',p==='all'?selectedPeriods.size===3:(selectedPeriods.size!==3&&selectedPeriods.has(p)));});};
 c.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{if(typeof selectedPeriods==='undefined')return;const p=b.dataset.p;if(p==='all'){selectedPeriods.clear();['1947-1952','1953-1958','1959-1965'].forEach(x=>selectedPeriods.add(x));}else if(selectedPeriods.size===3){selectedPeriods.clear();selectedPeriods.add(p);}else if(selectedPeriods.has(p)){selectedPeriods.delete(p);if(!selectedPeriods.size)['1947-1952','1953-1958','1959-1965'].forEach(x=>selectedPeriods.add(x));}else selectedPeriods.add(p);if(typeof paintGlobalFilters==='function')try{paintGlobalFilters()}catch(e){}paintP();});
 c.querySelector('#bubRange').oninput=e=>setBub(e.target.value);c.querySelectorAll('[data-b]').forEach(b=>b.onclick=()=>{const d=+b.dataset.b;setBub(d?(+$('bubRange').value+d):54)});
 return c;}
const sc=$('studyContent');if(sc){const inject=()=>{if(document.querySelector('[data-study="settings"].on')&&!$('v9SetCard')){const pm=$('presModeCard');const card=settingsCard();if(pm)pm.after(card);else{const h3=sc.querySelector('h3');if(h3)h3.before(card);else sc.prepend(card);}}};new MutationObserver(()=>setTimeout(()=>{inject();bubblize();},20)).observe(sc,{childList:true,subtree:true});inject();}
console.log('V9 layer ready');})();
